Loop topics practiced
HarisButt090/ROR-Training pull request #14
Opened 2024-10-16 09:45 UTC by HarisButt090

### Description
Topics of this pull request include while and until loop, next and break keyword, and recursion. Practiced 2 problem of recursion through while loop and recursion both.

2024-10-17 07:12 UTC, 786minal requested changes

2024-10-17 07:12 UTC, minal-builds commented on 10 - Loops/the_break_keyword.rb
> +money_sentence = "I love $ in the morning, $ in the afternoon, and $ at night"
Add description of your working.

2024-10-17 07:12 UTC, 786minal commented on 10 - Loops/the_next_keyword.rb
> +money_sentence = "I love $ in the morning, $ in the afternoon, and $ at night"
Add proper description for your working

2024-10-17 07:12 UTC, 786minal commented on 10 - Loops/the_next_keyword.rb
> +# while current_index <= final_index #run until current is greater the final index
Please add a function to make it more reusable.

2024-10-17 07:12 UTC, 786minal commented on 10 - Loops/the_next_keyword.rb
> +while current_index <= final_index #run until current is greater the final index
Please add a function to make it more reusable.

2024-10-17 07:12 UTC, 786minal commented on 10 - Loops/the_while_loop.rb
> +while count < 10 # it will return until count is greater than 10
Please add a function to make it more reusable.

2024-10-17 07:12 UTC, 786minal commented on 10 - Loops/the_while_loop.rb
> +while letter.length < 5 # Run until the length of of letter is greater > 5
Please add a function to make it more reusable.

2024-10-18 05:14 UTC, 786minal requested changes

2024-10-18 05:14 UTC, 786minal commented on 10 - Loops/the_next_keyword.rb
> +def find_dollars_while(money_sentence)
rename function like` find_dollars_sign_indices`

2024-10-18 05:14 UTC, 786minal commented on 10 - Loops/the_next_keyword.rb
> +puts "Find Dollar method result using while loop"
Task is to find dollar sign index using while loop so make statement accordingly
`puts "Dollar sign positions (using while loop):"`

2024-10-18 05:14 UTC, 786minal commented on 10 - Loops/the_while_loop.rb
> +  puts letter #
remove `# `over this line

2024-10-18 05:14 UTC, 786minal commented on 10 - Loops/the_until_loop.rb
> +#
remove extra  `#`    over this line

2024-10-18 05:14 UTC, 786minal commented on 10 - Loops/recursion_i.rb
> +#
remove extra `#` over this line

2024-10-18 05:36 UTC, 786minal approved these changes

2024-10-18 05:56 UTC, merged