Haris/v1/array2 exercises
HarisButt090/ROR-Training pull request #17
Opened 2024-10-18 06:53 UTC by HarisButt090

### Description
Topics of this PR include any and all, find and detect, include, min and max methods and splat/spung arguments that I used in the coding exercises

2024-10-22 06:27 UTC, 786minal requested changes

2024-10-22 06:27 UTC, minal-builds commented on 14 - Arrays II/coding_exercise_custom_max.rb
> +def custom_max(array)
Try to solve it using method **for** ,  **each**

2024-10-22 13:36 UTC, 786minal requested changes

2024-10-22 13:36 UTC, 786minal commented on 14 - Arrays II/coding_exercise_custom_max.rb
> +
fix indentation as well as write

max = element if max < element

2024-10-24 06:20 UTC, 786minal approved these changes

2024-10-24 06:24 UTC, merged